# Generated by Django 5.2.1 on 2025-05-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_projects_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_by', models.BigIntegerField()),
                ('img_name', models.CharField(blank=True, max_length=255, null=True)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
